version: "3.9"
services:
  auth_service:
    image: pgw/auth-api-server:latest
    restart: always
    environment:
      - PGW_AUTH_APP_DATABASE_FILENAME=/db_creds.yaml
    volumes:
     - ./auth-service/db_creds.yaml:/db_creds.yaml:ro
    networks:
      - backend
  payment_processor_service:
    image: pgw/payment-processor-api-server:latest
    restart: always
    environment:
      - PGW_PAYMENT_PROCESSOR_APP_OPTIONS_CREDITCARDS_FILENAME=/edge_cases_credit_cards.yaml
    volumes:
     - ./payment-processor-service/edge_cases_credit_cards.yaml:/edge_cases_credit_cards.yaml:ro
    networks:
      - backend

networks:
  backend:
    driver: bridge
